import React from 'react';

const petsDB2 = {
  users: [
    {
      id: 1,
      createdDate: 0,
      name: 'Mister X',
      admin: true,
    },
    {
      id: 2,
      createdDate: 0,
      name: 'Pietje',
      admin: false,
    },
  ],
  admins: [{}],
  pets: [
    {
      id: 1,
      createdDate: 0,
      type: 'Dog',
      name: 'Doggy',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/dog.jpeg',
    },
    {
      id: 2,
      createdDate: 0,
      type: 'Cat',
      name: 'Catty',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/cat.jpeg',
    },
    {
      id: 3,
      createdDate: 0,
      type: 'Bird',
      name: 'Birdy',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/bird.jpeg',
    },
    {
      id: 4,
      createdDate: 0,
      type: 'Fish',
      name: 'Fishy',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/fish.jpeg',
    },
    {
      id: 5,
      createdDate: 0,
      type: 'Dog',
      name: 'Doggy',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/dog.jpeg',
    },
    {
      id: 6,
      createdDate: 0,
      type: 'Cat',
      name: 'Catty',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/cat.jpeg',
    },
    {
      id: 7,
      createdDate: 0,
      type: 'Bird',
      name: 'Birdy',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/bird.jpeg',
    },
    {
      id: 8,
      createdDate: 0,
      type: 'Fish',
      name: 'Fishy',
      status: 'Adopted',
      breed: 'Poodle',
      color: 'Brown',
      height: 50,
      weight: 20,
      hypoallergenic: 'No',
      diet: 'No',
      bio: 'Bla bla bla bla bla',
      image: '../petImages/fish.jpeg',
    },
  ],
};

export { petsDB2 };

const petsDB = {
  pets: [
    {
      id: 1,
      createdDate: 0,
      type: 'Dog',
      name: 'Doggy',
      status: 'adopted',
      image: '../petImages/dog.jpeg',
    },
    {
      id: 2,
      createdDate: 0,
      type: 'Cat',
      name: 'Catty',
      status: 'adopted',
      image: '../petImages/cat.jpeg',
    },
    {
      id: 3,
      createdDate: 0,
      type: 'Bird',
      name: 'Birdy',
      status: 'adopted',
      image: '../petImages/bird.jpeg',
    },
    {
      id: 4,
      createdDate: 0,
      type: 'Fish',
      name: 'Fishy',
      status: 'adopted',
      image: '../petImages/fish.jpeg',
    },
    {
      id: 5,
      createdDate: 0,
      type: 'Dog',
      name: 'Doggy',
      status: 'adopted',
      image: '../petImages/dog.jpeg',
    },
    {
      id: 6,
      createdDate: 0,
      type: 'Cat',
      name: 'Catty',
      status: 'adopted',
      image: '../petImages/cat.jpeg',
    },
    {
      id: 7,
      createdDate: 0,
      type: 'Bird',
      name: 'Birdy',
      status: 'adopted',
      image: '../petImages/bird.jpeg',
    },
    {
      id: 8,
      createdDate: 0,
      type: 'Fish',
      name: 'Fishy',
      status: 'adopted',
      image: '../petImages/fish.jpeg',
    },
  ],
};

export default petsDB;
